### PR TITLE
h5set_extent/H5Dset_extent support extending dimensions beyond 2^31

### PR DESCRIPTION
**Pull request by hpages**
Hi Mike,

Right now, `h5set_extent`/`H5Dset_extent` fail to extend dimensions beyond 2^31:
```
library(rhdf5)
tmpfile <- tempfile()
h5createFile(tmpfile)
h5createDataset(tmpfile, "A", dims=0, maxdims=3e9, storage.mode="integer", chunk=16384)

h5ls(tmpfile, all=TRUE)[c("dim", "maxdim")]
#   dim     maxdim
# 0   0 3000000000

h5set_extent(tmpfile, "A", dims=1e9)
h5ls(tmpfile, all=TRUE)[c("dim", "maxdim")]
#          dim     maxdim
# 0 1000000000 3000000000

h5set_extent(tmpfile, "A", dims=2e9)
h5ls(tmpfile, all=TRUE)[c("dim", "maxdim")]
#          dim     maxdim
# 0 2000000000 3000000000

h5set_extent(tmpfile, "A", dims=3e9)
# Error in H5Dset_extent(did, dims) : 
#   HDF5. Dataset. Unable to initialize object.
# In addition: Warning message:
# In H5Dset_extent(did, dims) : NAs introduced by coercion to integer range
h5ls(tmpfile, all=TRUE)[c("dim", "maxdim")]
#          dim     maxdim
# 0 2000000000 3000000000
```
The change I propose is straightforward.

Thanks!
H.

```
> sessionInfo()
R version 3.5.1 Patched (2018-08-01 r75051)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /home/hpages/R/R-3.5.r75051/lib/libRblas.so
LAPACK: /home/hpages/R/R-3.5.r75051/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rhdf5_2.25.4

loaded via a namespace (and not attached):
[1] compiler_3.5.1 Rhdf5lib_1.3.1
```

### CODE REVIEW

**Comment by hpages** [comment]
Thanks Mike. Any chance you can push this to git.bioconductor.org? I need this for a new feature I'm working on in HDF5Array and I'd like to make it available in Bioc devel. Thanks again!

**Comment by grimbough** [comment]
This should be done now.  I made the mistake of also committing the changes to work with HDF5 1.10 before realising that I couldn't commit the relevant version of *Rhdf5lib*.  Hopefully I've reverted those for the time being - we'll see on the next build report.

**Comment by hpages** [comment]
Hi Mike,

It looks like today you reverted again:
```
commit 73f8a8521efa3424e1002a703acb8701b7fbb87e
Author: Mike Smith <grimbough@gmail.com>
Date:   Thu Aug 23 13:12:39 2018 +0200

    bump version

commit ac8acb31d31805ec0dc0b30a5803b8953cdfb00a
Author: Mike Smith <grimbough@gmail.com>
Date:   Thu Aug 23 13:11:31 2018 +0200

    Revert "Revert "fix type for 'printing' hid_t to string""
    
    This reverts commit ed2b054d0d05a9789685c17036043ecfa80272b5.

commit 5d144b33d28acf4830b1cf67a58bc8f07fa96a63
Author: Mike Smith <grimbough@gmail.com>
Date:   Thu Aug 23 13:11:02 2018 +0200

    Revert "Revert "Updates to work with HDF5 1.10.2""
    
    This reverts commit 46fc63c8f343cc81bca2d8050be2f9c90b584984.
```
Was this intentional?

The current version (2.25.7) doesn't compile for me:
```
hpages@spectre:~/git.bioconductor.org/software$ R CMD INSTALL rhdf5
* installing to library ‘/home/hpages/R/R-3.5.r75051/library’
* installing *source* package ‘rhdf5’ ...
** libs
gcc -I"/home/hpages/R/R-3.5.r75051/include" -DNDEBUG  -I"/home/hpages/R/R-3.5.r75051/library/Rhdf5lib/include" -I/usr/local/include   -fpic  -g -O2  -Wall -c H5constants.c -o H5constants.o
H5constants.c: In function ‘_H5constants’:
H5constants.c:64:82: error: ‘H5F_LIBVER_V18’ undeclared (first use in this function)
   int const_H5F_LIBVER[4]       = {  H5F_LIBVER_EARLIEST,   H5F_LIBVER_LATEST,   H5F_LIBVER_V18 ,  H5F_LIBVER_V110  };
                                                                                  ^
H5constants.c:64:82: note: each undeclared identifier is reported only once for each function it appears in
H5constants.c:64:100: error: ‘H5F_LIBVER_V110’ undeclared (first use in this function)
   int const_H5F_LIBVER[4]       = {  H5F_LIBVER_EARLIEST,   H5F_LIBVER_LATEST,   H5F_LIBVER_V18 ,  H5F_LIBVER_V110  };
                                                                                                    ^
In file included from /home/hpages/R/R-3.5.r75051/library/Rhdf5lib/include/hdf5.h:37:0,
                 from myhdf5.h:11,
                 from H5G.h:8,
                 from H5constants.c:1:
/home/hpages/R/R-3.5.r75051/library/Rhdf5lib/include/H5Spublic.h:26:23: warning: overflow in implicit constant conversion [-Woverflow]
 #define H5S_UNLIMITED ((hsize_t)(hssize_t)(-1))
                       ^
H5constants.c:88:43: note: in expansion of macro ‘H5S_UNLIMITED’
   hid_t const_H5S_UNLIMITED[1]       = {  H5S_UNLIMITED };
                                           ^
/home/hpages/R/R-3.5.r75051/etc/Makeconf:159: recipe for target 'H5constants.o' failed
make: *** [H5constants.o] Error 1
ERROR: compilation failed for package ‘rhdf5’
* removing ‘/home/hpages/R/R-3.5.r75051/library/rhdf5’
* restoring previous ‘/home/hpages/R/R-3.5.r75051/library/rhdf5’
```
FWIW after the 1st revert (version 2.25.6, was pushed to git.bioconductor.org on Aug 22), and before this 2nd revert, it was working fine.

Thanks!

**Comment by grimbough** [comment]
I don't know how to 'un revert' so that's the equivalent of setting it back to the version that works with HDF 1.10. It  should work with the version of Rhdf5lib that's currently in the master branch of both GitHub and git.bioconductor 

That error suggests your still using an old version of Rhdf5lib

**Comment by hpages** [comment]
Ah that's it!

It's really disappointing that `R CMD INSTALL` doesn't check the deps **before** the compilation step. rhdf5 requires Rhdf5lib >= 1.3.2 and I had Rhdf5lib 1.3.1 but compilation failed before `R CMD INSTALL` had a chance to tell me about this version mismatch.

I installed the latest Rhdf5lib (1.3.2) and everything seems to be working fine now. Thanks!
